import { NextResponse } from 'next/server';
import https from 'https';
import { Readable } from 'stream';
import { OSIRIS_UA } from '@/lib/httpJson';
import { parseTile, trafficTileUrl } from '@/lib/traffic-tiles';

/**
 * One TomTom Traffic Flow tile, with the key added here rather than in the
 * browser. See ../../route.ts for why the layer is gated at all.
 */
export const dynamic = 'force-dynamic';

export async function GET(_req: Request, ctx: { params: Promise<{ z: string; x: string; y: string }> }) {
  const key = process.env.TOMTOM_API_KEY;
  if (!key) return NextResponse.json({ error: 'Traffic is off: TOMTOM_API_KEY is not set.' }, { status: 404 });
  const { z, x, y } = await ctx.params;
  const tile = parseTile(z, x, y);
  if (!tile) return NextResponse.json({ error: 'Bad tile coordinates' }, { status: 400 });

  return new Promise<Response>(resolve => {
    const req = https.get(trafficTileUrl(tile, key), { headers: { 'User-Agent': OSIRIS_UA, Accept: 'image/png' }, timeout: 15000 }, res => {
      const status = res.statusCode ?? 0;
      if (status !== 200) {
        res.resume();
        resolve(NextResponse.json({ error: `TomTom answered ${status}` }, { status: status === 403 ? 403 : 502 }));
        return;
      }
      resolve(new Response(Readable.toWeb(res) as ReadableStream, {
        headers: {
          'Content-Type': res.headers['content-type'] || 'image/png',
          // Flow tiles are regenerated by the provider every minute or so; a
          // short shared cache keeps a pan from spending the day's quota twice.
          'Cache-Control': 'public, max-age=60',
        },
      }));
    });
    req.on('timeout', () => req.destroy(new Error('timeout')));
    req.on('error', e => resolve(NextResponse.json({ error: e.message }, { status: 502 })));
  });
}
